'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinNUT_Client.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1025() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1025", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1026() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1026", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1028() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1028", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1032() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1032", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1040() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1040", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1057() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1057", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1058() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1058", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1060() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1060", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1064() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1064", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1072() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1072", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1079() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1079", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1080() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1080", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1092() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1092", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1096() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1096", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1104() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1104", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1121() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1121", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1122() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1122", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1124() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1124", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1128() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1128", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1136() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1136", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1152() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1152", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1216() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1216", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1280() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1280", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _1344() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("1344", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _2001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("2001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property _2002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("2002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application shut down at.
        '''</summary>
        Public ReadOnly Property App_Event_Str_01() As String
            Get
                Return ResourceManager.GetString("App_Event_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Battery_Charged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Charged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Battery_Charging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Charging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Battery_Discharging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Discharging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Delete_LogFile_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete_LogFile_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous preferences data detected in the Registry..
        '''</summary>
        Public ReadOnly Property DetectedPreviousPrefsData() As String
            Get
                Return ResourceManager.GetString("DetectedPreviousPrefsData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old ups.ini imported
        '''Ini File Moved to {0}.old.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_01() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old ups.ini imported.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_02() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reconnection In Progress.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_03() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Try {0} of {1}.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_04() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Connected.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_05() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connected.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_06() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On Line.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_07() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On Battery ({0}%).
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_08() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Low Battery.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_09() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Battery OK.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_10() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown UPS Name.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_11() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lost Connect To {0}:{1}.
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_12() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong Login ID (Username or Password).
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_13() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restarting WinNUT after waking up from Windows..
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_14() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows standby. WinNUT will disconnect..
        '''</summary>
        Public ReadOnly Property Frm_Main_Str_15() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Str_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Battery_Charge : {0}
        '''Remaining Time : {1}.
        '''</summary>
        Public ReadOnly Property Frm_Shutdown_Str_01() As String
            Get
                Return ResourceManager.GetString("Frm_Shutdown_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Available : Version {0}.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_01() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show ChangeLog.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_02() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide ChangeLog.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_03() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update WinNUT-Client Now?
        '''Ok to Close WinNut and Install New Version
        '''Cancel to Save Msi and Install Later.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_04() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download New Version from :.
        '''</summary>
        Public ReadOnly Property Frm_Update_Str_05() As String
            Get
                Return ResourceManager.GetString("Frm_Update_Str_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/nutdotnet/WinNUT-Client.
        '''</summary>
        Public ReadOnly Property GitHub_URL() As String
            Get
                Return ResourceManager.GetString("GitHub_URL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WinNut Preferences Changed.
        '''</summary>
        Public ReadOnly Property Log_Str_01() As String
            Get
                Return ResourceManager.GetString("Log_Str_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection to Nut Host {0}:{1} Established.
        '''</summary>
        Public ReadOnly Property Log_Str_02() As String
            Get
                Return ResourceManager.GetString("Log_Str_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection to Nut Host {0}:{1} Failed: {2}.
        '''</summary>
        Public ReadOnly Property Log_Str_03() As String
            Get
                Return ResourceManager.GetString("Log_Str_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatic Reconnection.
        '''</summary>
        Public ReadOnly Property Log_Str_04() As String
            Get
                Return ResourceManager.GetString("Log_Str_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnected from Nut Host.
        '''</summary>
        Public ReadOnly Property Log_Str_05() As String
            Get
                Return ResourceManager.GetString("Log_Str_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Try Reconnect {0} / {1}.
        '''</summary>
        Public ReadOnly Property Log_Str_06() As String
            Get
                Return ResourceManager.GetString("Log_Str_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Retry reached. Wait for manual Reconnection.
        '''</summary>
        Public ReadOnly Property Log_Str_07() As String
            Get
                Return ResourceManager.GetString("Log_Str_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conditions met for launching the Extinguishing Process.
        '''</summary>
        Public ReadOnly Property Log_Str_08() As String
            Get
                Return ResourceManager.GetString("Log_Str_08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancellation of the Extinguishing Process.
        '''</summary>
        Public ReadOnly Property Log_Str_09() As String
            Get
                Return ResourceManager.GetString("Log_Str_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Update Available.
        '''</summary>
        Public ReadOnly Property Log_Str_10() As String
            Get
                Return ResourceManager.GetString("Log_Str_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0} Available.
        '''</summary>
        Public ReadOnly Property Log_Str_11() As String
            Get
                Return ResourceManager.GetString("Log_Str_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop condition imposed by the NUT server.
        '''</summary>
        Public ReadOnly Property Log_Str_12() As String
            Get
                Return ResourceManager.GetString("Log_Str_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old preferences were not detected in your system..
        '''</summary>
        Public ReadOnly Property ManageOldPrefsToolstripMenuItem_Disabled_TooltipText() As String
            Get
                Return ResourceManager.GetString("ManageOldPrefsToolstripMenuItem_Disabled_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old preferences detected. Click to run the import wizard..
        '''</summary>
        Public ReadOnly Property ManageOldPrefsToolstripMenuItem_Enabled_TooltipText() As String
            Get
                Return ResourceManager.GetString("ManageOldPrefsToolstripMenuItem_Enabled_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property regedit_exe_14_100_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("regedit_exe_14_100_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save WinNUT Registry Key.
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_BackupLocationTitle() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_BackupLocationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The old preferences have been backed up to {0}.
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_BackupProcedureCompleted() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_BackupProcedureCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The upgrade process was cancelled: using default settings..
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_Cancelled() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_Cancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The old preferences have been removed from your Registry..
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_DeleteProcedureComplete() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_DeleteProcedureComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred during the upgrade procedure:
        '''
        '''{0}
        '''
        '''Please correct the error, or cancel the upgrade dialog to continue with the default settings..
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_ErrorEncountered() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_ErrorEncountered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The old preferences have been imported..
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_ImportProcedureCompleted() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_ImportProcedureCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No preferences detected.
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_NoPrefsExistCaption() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_NoPrefsExistCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No preferences were detected in the Registry. Unable to continue..
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_NoPrefsExistError() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_NoPrefsExistError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There were {0} unknown preferences. See log for more details..
        '''</summary>
        Public ReadOnly Property UpgradePrefsDialog_UnmatchedPairs() As String
            Get
                Return ResourceManager.GetString("UpgradePrefsDialog_UnmatchedPairs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ups_104x104() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ups_104x104", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unavailable.
        '''</summary>
        Public ReadOnly Property VariableUnavailable() As String
            Get
                Return ResourceManager.GetString("VariableUnavailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ViewLogFile_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewLogFile_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property WinNut() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("WinNut", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property WinNUT_Updater() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("WinNUT_Updater", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property XP_Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XP_Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
